name: Run tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pico-sdk/develop
      uses: actions/checkout@v2
      with:
        repository: raspberrypi/pico-sdk
        ref: develop
        path: pico-sdk

    - name: Checkout pico-sdk submodules
      run: cd pico-sdk && git submodule update --init

    - name: Install toolchain dependencies
      run:  sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib

    - name: Hello
      run: pwd && echo $SHELL 
    # - name: Configure CMake
    #   # Use a bash shell so we can use the same syntax for environment variable
    #   # access regardless of the host operating system
    #   shell: bash
    #   working-directory: ${{github.workspace}}/pico-examples/build
    #   # Note the current convention is to use the -S and -B options here to specify source 
    #   # and build directories, but this is only available with CMake 3.13 and higher.  
    #   # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
    #   run: PICO_SDK_PATH=../../pico-sdk cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    # - name: Checkout pico-project-generator
    #   uses: actions/checkout@v2
    #   with:
    #     path: pico-project-generator

    # - name: Build
    #   working-directory: ${{github.workspace}}/pico-examples/build
    #   shell: bash
    #   # Execute the build.  You can specify a specific target with "--target <NAME>"
    #   run: cmake --build . --config $BUILD_TYPE --parallel ${{steps.core_count.outputs.output}}
